## This script pulls down the raw gymnastics score files from GitHub.
library(knitr)
library(plotly)
library(scales)
library(DT)
library(leaflet)
library(gganimate)
library(corrplot)
library(GGally)
library(ggmap)
library(shiny)
library(MASS)
library(lme4)
library(arm)
library(pROC)
library(MLmetrics)
library(viridis)
library(RSelenium)
library(rvest)
library(randomForest)
library(FNN)
library(caret)
library(pls)
library(stringr)
library(devtools)
library(splines)
library(RecordLinkage)
library(rsconnect)
library(tidyverse)
library(pubtheme)

in_earlier_scores <- read.csv("Case_Study_1-Gymnastics/data/data_2017_2021.csv")
in_later_scores   <- read.csv("Case_Study_1-Gymnastics/data/data_2022_2023.csv")
