---
title: "Gymastics Case Study, Part 2"
author: "425/625"
date: "September 06, 2023"
output:
  pdf_document: default
  word_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 2 - Planning and Modeling Gymnast Abilities

In Part 2, you will map out your plan-of-attack of how you will generate the outputs mentioned in your Part 1 submission about end deliverables.  

DONE 1. Think about the 3-4 main steps that need to be done (for example data cleaning, modeling, etc., or something more specific to this project) and the details of what needs to be done in each of those steps.  
DONE 2. For each of those main steps, think about how to break the work into 3 parts that can be worked on in parallel by the 3 members of your group. 
DONE 3. Create a `main.r` script that looks like this that will serve as a sort of outline for all of your scripts or functions

```
## main.r
## This script runs all code related to gymnastics case study. 
## It reads data and generates all outputs. 

source('R/get.data.r')
source('R/prep.data.r')
source('R/fit.model.r')
## etc

```

If you use functions instead of scripts, it might look like this

```
## main.r
## This script runs all code related to gymnastics case study. 
## It reads data and generates all outputs. 

## Load functions here



## Get and prep data, fit models, etc
df = get.data()
dc = prep.data(df)
m  = fit.model(dc)
## etc

```

4. For each of your 3-4 main steps, create a new file containing either functions or scripts and write an outline in that file.  For example, a script `prep.data.r` might look like this

```
## prep.data.r
## This script prepares the data from the csv files for modeling

## First, deduplicate names, clean dates, etc

## Then, create some predictors

## etc (add more subheadings for other main tasks)

```

Think about the inputs, outputs, and how the data will need to be structured at each stage, and write notes to yourself in these files about that.  Note that you are creating `.R` files, not `.Rmd` files

5. (Optional) If you write functions, you can try using the package `vizdataflow` https://github.com/bmacGTPM/vizdataflow to visualize your workflow. This is a package I started developing and it's only like Version 0.1 alpha, but you still might find it useful. This is purely optional. If you do use it, I'd be interested in your feedback. What do you wish the packages could do?

Writing modular code has several benefits:

  - Easier to read and navigate through the code
  - Easier to reproduce (by self or someone else). Easier update with new data, additional data
  - Easier to delegate tasks and work on things in parallel
  - Easier to update one part of the process.
  - For this case study in particular, it may be easier to change between Tokyo 2020 and Paris 2024 rules

6. Once you have finished creating this scaffolding, build your first model for gymnast abilities/scores in each event. Think about what you need to generate for the next steps. Start simple. You'll have a chance to update this later. 


## Deliverables

Submit a `.zip` file to Gradescope with your R files, including `main.r` from #3 above and any files used by `main.r` from #4. Some files will have only comments outlining what you plan to do. The files with your data prep and modeling will have some code in them (from #6). 

