---
title: "Gymnastic Case Study, Part 4"
author: "425/625"
date: '2023-09-25'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Outcomes for thousands of combinations of gymnasts and apparatus

In this part you will extend the work you did in Part 3 but instead of using one fixed set of teams, gynmasts, and gymnast-apparatus pairings, you will check many  thousands of combinations of those. 

1. You can first do a back-of-the-napkin estimate for how long your simulation will take to run with the number of combinations you plan to check. 
2. You may be able to reduce the number of combinations of gymnasts from "all combinations" to "combinations that would reasonably be considered" by removing some gymnasts based on some criteria. Then you can revisit #1. 
3. You can first code up your solution in whatever way seems most intuitive to you. 4. If you hit hurdles, or you realize your computation time is higher than expected, you can then modify that code to make it computational more efficient.  This likely includes using vectorized operations whenever possible.  Note that, for example, `rnorm`, `rbinom`, `rbeta`, etc., can take vector inputs for the `mean`, `sd`, `prob`, `scale1`, `scale2`, so you sample for multiple gymnasts at once, if desired. 

Your deliverable is your updated code that generates your outcomes for thousands of combinations, and a .csv file that contains the results with one line per combinations of gymnasts-apparatus, and columns that contain the results and other information that you think will be important for communicating the results to the end user (e.g. country).  
